### ISSUE TITLE
Support for Chrome extensions?

### ISSUE THREAD

**Issue by stickyburn** [herber/cargo#32]
Hello,

I believe supporting Chrome extensions are dependent more on Electron than Cargo itself, but is there a way to add Chrome extensions on the browser? Things like React, Ember devtools would be really great! 
I would love to contribute to this feature request if I can :) 

Thanks for this awesome browser!

**Comment by herber** [comment]
Hi there! 

I'm glad you like Cargo. 🤘

Honestly, I don't think support for Chrome extensions is feasible. By default Electron only supports a small set of [Chrome extension APIs](https://www.electronjs.org/docs/api/extensions), so we would have to implement a lot of them ourselves. See [Web Extensions on MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions). Also, many browser extensions use features, which Cargo does not have, like [page actions](https://developer.chrome.com/docs/extensions/reference/pageAction/) or popups. 

Regarding React or Ember dev tools, I think the main problem would be to give the extensions access to Electron's custom Chrome devtools, which as far as I know is not supported.

We also have to keep security in mind. Chrome extensions are heavily sandboxed and even checked by Google Employees. Since Electron's minimal Chrome extension API does not support permissions or isolation, we would essentially give untrusted code full access to a computer.

I'm sorry to disappoint you 😔, but I don't think there is an easy way to add actually useful support for browser extensions. 

If you have any idea on how we could overcome these issues, please let me know.
